name: Test Artifact Upload

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: echo "Hello" > test.txt

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: test.txt
